version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - EASTERN_STATE_BUCKET=eastern-state
            - EASTERN_STATE_NAME=airflow
            - EASTERN_STATE_ENV=dev
            - S3_STAGING_BUCKET=phl-etl-staging-dev
            - S3_SCHEMA_BUCKET=phl-schemas
            - BEV_TAX_MSSQL_CONN_STRING=${BEV_TAX_MSSQL_CONN_STRING}
            - CARTO_CONN_STRING=${CARTO_CONN_STRING}
            - GEODB2_CONN_STRING=${GEODB2_CONN_STRING}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8888:8080"
        command: webserver

    scheduler:
        build: .
        restart: always
        depends_on:
            - postgres
            - webserver
        volumes:
            - ./requirements.txt:/requirements.txt:ro
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        environment:
            - AIRFLOW__CORE__FERNET_KEY=9IoTgQ_EJ0hCsamBU3Mctc7F9OkODnndOKCwkwXCAA
            - EASTERN_STATE_BUCKET=eastern-state
            - EASTERN_STATE_NAME=airflow
            - EASTERN_STATE_ENV=dev
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - S3_STAGING_BUCKET=phl-etl-staging-dev
            - S3_SCHEMA_BUCKET=phl-schemas
            - BEV_TAX_MSSQL_CONN_STRING=${BEV_TAX_MSSQL_CONN_STRING}
            - CARTO_CONN_STRING=${CARTO_CONN_STRING}
            - GEODB2_CONN_STRING=${GEODB2_CONN_STRING}
        command: scheduler -n 5
